FROM nvcr.io/nvidia/pytorch:22.11-py3

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

#RUN sed -i.bak -e "s%http://[^ ]\+%http://ftp.jaist.ac.jp/pub/Linux/ubuntu/%g" /etc/apt/sources.list

RUN apt-get update &&\
    DEBIAN_FRONTEND=noninteractive apt-get -y install gosu
# timezone setting
ENV TZ=Asia/Tokyo

RUN pip install --no-cache-dir scikit-image==0.20.0 \
                               statsmodels==0.13.5 \
                               memory-profiler==0.61.0 \
                               seaborn==0.12.2 \
                               pydot==1.4.2 \
                               h5py==3.8.0 \
                               imageio==2.27.0 \
                               pydicom==2.2.2 \
                               python-gdcm==3.0.19 \
                               SimpleITK==2.1.1 \
                               future==0.18.2 \
                               tensorflow==2.10.0

# install opacus
RUN pip install --no-deps --no-cache-dir opacus==1.4.0 \
                                         opt-einsum==3.3.0

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]